spring:
  application:
    name: api-clone-picpay
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/picpaycloneDB
    username: postgres
    password: 321
  api:
       versao: 1.0.0

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
server:
  port: 8082
